### ISSUE TITLE
When running tests, NullPointerException is thrown from OWL manager method loadOntologyFromOntologyDocument

### ISSUE THREAD

**Issue by joephayes** [EcoStruxure/OLGA#11]
**Describe the bug**
When running tests on master branch, NullPointerException is thrown from OWL manager method loadOntologyFromOntologyDocument

**To Reproduce**
1. Run the following command: `mvn clean install --projects OLGA-Core`

**Expected behavior**
All tests pass.

**Actual behavior**
Several tests fail with a NullPointerException thrown by the call to `loadOntologyFromOntologyDocument`. For example,

```
[INFO] Running semanticstore.ontology.library.generator.visitor.OLGAVisitorDSPTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in semanticstore.ontology.library.generator.visitor.OLGAVisitorDSPTest
[ERROR] semanticstore.ontology.library.generator.visitor.OLGAVisitorDSPTest  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
        at semanticstore.ontology.library.generator.visitor.OLGAVisitorDSPTest.setUpBeforeClass(OLGAVisitorDSPTest.java:238)

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS, version 10.14.6, OpenJDK 1.8.0_232
 - Browser n/a
 - Version n/a 

**Additional context**
I had to add the following exclusion to the maven-invoker-plugin in OLGA-Core pom.xml:

```
<exclusion>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-jdk14</artifactId>
</exclusion>

```

**Comment by radissoa** [comment]
This is an issue with the surefire plugin, I am looking into it.
