### ISSUE TITLE
Add Turtle support to OLGA web service

### ISSUE THREAD

**Issue by joephayes** [EcoStruxure/OLGA#12]
Add turtle file support to the OLGA web service (CLI already supports turtle files)

Currently when I try to submit a turtle file to the web service I get the following error:

```
{
    "timestamp": "2020-01-28T16:07:53.065Z",
    "status": 415,
    "error": "Unsupported Media Type",
    "exception": "org.springframework.web.HttpMediaTypeNotSupportedException",
    "message": "Content type 'text/turtle' not supported",
    "path": "/Ontology/OLGAsaas/1.0.0/1.0/generate"
}
```

**Comment by charbull** [comment]
This should have been resolved with the OWL API update?

**Comment by joephayes** [comment]
Unfortunately no. :-(

CLI works fine with turtle but the web service throws the Unsupported media type error (I tried both the `text/turtle` and `application/x-turtle` media types in the `Content-Type` header).

I'll dig into it.

**Comment by joephayes** [comment]
This line is the issue: https://github.com/EcoStruxure/OLGA/blob/master/OLGA/OLGA-Ws/src/main/java/semanticstore/ontology/library/generator/api/interfaces/GeneratorApi.java#L56 - as defined, the web method can only consume XML. I'll work on a fix.
