### ISSUE TITLE
Generation does not work using docker container.

### ISSUE THREAD

**Issue by meberl** [EcoStruxure/OLGA#27]
**Describe the bug**
The generation does not seem to run using service through the docker image. 
Response is:
```
{
  "content-disposition": "attachment;filename=test.zip",
  "content-length": "0",
  "date": "Tue, 10 Nov 2020 12:26:40 GMT"
}
```

**To Reproduce**
1. Start OLGA container
2. Navigate to the swagger [endpoint](http://localhost:9090/Ontology/OLGAsaas/1.0.0/1.0/swagger-ui.html#/generator45controller)
3. Fill the values with the ones from [Webservice-User-Guide](https://github.com/EcoStruxure/OLGA/wiki/Webservice-User-Guide) 
4. Press "Try it out" button
5. See error

**Expected behavior**
It should download the result, but the ontology file doesn't seem to be picked up by service.

**Log**
```
2020-11-10 12:26:40 INFO GeneratorController:90 - Operation Starts

2020-11-10 12:26:40 INFO GeneratorController:96 - Parsing Inputs

2020-11-10 12:26:40 INFO GeneratorController:104 - Invoke Olga Service

2020-11-10 12:26:40 ERROR OlgaService:223 - java.nio.file.NoSuchFileException: ./temp/b26d57b2-7897-435a-91e5-328b15d44020

2020-11-10 12:26:40 ERROR OlgaService:123 - java.nio.file.NoSuchFileException: ./temp/b26d57b2-7897-435a-91e5-328b15d44020

2020-11-10 12:26:40 ERROR OlgaService:78 - java.nio.file.NoSuchFileException: ./temp/b26d57b2-7897-435a-91e5-328b15d44020

2020-11-10 12:26:40 ERROR GeneratorController:133 - java.nio.file.NoSuchFileException: ./temp/b26d57b2-7897-435a-91e5-328b15d44020

./temp/b26d57b2-7897-435a-91e5-328b15d44020

2020-11-10 12:26:40 INFO GeneratorController:137 - Clean up

2020-11-10 12:26:40 INFO GeneratorController:142 -
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera

**Additional context**
I've built and run the OLGA docker container under windows.
Also, the documentation has not been updated since the endpoint parameters was switched to Multipart-Form. ´

**Comment by radissoa** [comment]
Hello Moritz,

I have been able to reproduce the error. I will look into the problem.

**Comment by meberl** [comment]
Hi Alexis, 
are there any news regarding this issue?

**Comment by radissoa** [comment]
Hello Moritz,

I have located the issue to this line https://github.com/EcoStruxure/OLGA/blob/81aaf0afdca933adf64f3b12b58406b90ce1a7dd/OLGA/OLGA-Ws/src/main/java/semanticstore/ontology/library/generator/utils/Helper.java#L116. I will fix when I have the time to test the change.

**Comment by charbull** [comment]
@radissoa hi do you need help on this?

**Comment by radissoa** [comment]
Hello Charbel, I figured out the issue. In fact, it is not really an issue, PR#14 introduced multipart files and the Olga webservice only accepts zip files as input now, as this was not updated in the wiki this created the issue that Moritz had. There is a choice to make here. Either we keep things as they are, or we give the user the ability to send olga either a zip file or a single owl file ? Personally, I favor the second option.

**Comment by charbull** [comment]
@radissoa thanks for looking this
I think we need to support both.
Removing the zip support will make Olga backward incompatible.
Can we add the single file support?

**Comment by meberl** [comment]
I wasn't aware that Olga expects a zip file, this is actually fine for me. It would be helpful if you could update the documentation/examples to reflect these changes.

**Comment by charbull** [comment]
Hi @meberl can we close this issue?

Thank you

**Comment by charbull** [comment]
@radissoa can we close this one?

**Comment by radissoa** [comment]
I will close it when i update the documentation, hopefully i can do it next week.

**Comment by radissoa** [comment]
I updated the wiki for the web service with the ne wimplementation
