### ISSUE TITLE
Support Turtle syntax Ontology files

### ISSUE THREAD

**Issue by joephayes** [EcoStruxure/OLGA#5]
In addition to RDF and OWL it would be great if OLGA supported Turtle syntax ontology files

**Comment by AlberTadrous** [comment]
Hi Joe,
As you know that OLGA built on top OWL API which still has problems in parsing Turtle files
https://github.com/owlcs/owlapi/issues/719

**Comment by joephayes** [comment]
It looks like that issue was fixed in the 5.1.4 release of OWL API (see https://github.com/owlcs/owlapi#bug-fixes-8) and OLGA uses version 5.1.5 - would it be possible to revisit supporting Turtle syntax?

**Comment by charbull** [comment]
I think this should be possible if we update the OWL API maven dependency.
Can someone try it out?

**Comment by joephayes** [comment]
When using the CLI a turtle file works with the current OWL API maven dependency - I had an error in my test turtle file! 🤦‍♂ 

However, I did notice that the OWL API dependency could be bumped to version 5.1.12 and I resolved a logging dependency issue with maven invoker plugin (when I ran the CLI I kept getting a slf4j version mismatch error). I will open a PR.
