### ISSUE TITLE
Example of submitting multiple ontology files to OLGA web service

### ISSUE THREAD

**Issue by joephayes** [EcoStruxure/OLGA#8]
Would it be possible to provide an example of how to submit multiple ontology files to the `/generate` endpoint?

**Comment by charbull** [comment]
through the CLI it is a matter of pointing to a folder where multiple ontologies are there.
I believe @AlberTadrous proposed a zip file or a post upload?

**Comment by joephayes** [comment]
a zip file upload would be great - is that feature work scheduled?

**Comment by joephayes** [comment]
PR https://github.com/EcoStruxure/OLGA/pull/14 implemented a zip file upload
